# Generated by Django 4.2.7 on 2023-11-28 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Coffee_Web_Shop', '0002_alter_order_order_date_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 28, 15, 59, 6, 266076)),
        ),
    ]
